{% macro upload_cortex_schema_sql(schema_name='ATTENDANCE') %}
{#
    Returns the SQL that copies the generated YAML from the model table to the stage.
    Uses same database/schema as create_cortex_stage (target or vars) so they match.
#}
{% set cortex_database = var('cortex_database') or target.database %}
{% set table_schema = var('cortex_target_schema', target.schema ~ '_cortex_schemas') %}
{% set stage_path = '@' ~ cortex_database ~ '.' ~ table_schema ~ '.CORTEX_ANALYST_STAGE/' ~ schema_name | lower ~ '.yml' %}
COPY INTO {{ stage_path }}
FROM (
    SELECT "yaml_content"
    FROM {{ target.database }}.{{ table_schema }}.generate_cortex_schemas
    WHERE "schema_name" = '{{ schema_name }}'
    ORDER BY "generated_at" DESC
    LIMIT 1
)
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = NONE COMPRESSION = NONE)
OVERWRITE = TRUE
SINGLE = TRUE
HEADER = FALSE
{% endmacro %}


{% macro upload_cortex_schema(schema_name='ATTENDANCE') %}
{#
    Upload generated Cortex Analyst YAML to a Snowflake stage (run-operation).
    Not needed if you use the model's post-hook; the model uploads automatically after each run.
#}
{% set cortex_stage = var('cortex_stage', '@CORTEX_ANALYST_STAGE') %}
{% set stage_path = cortex_stage ~ '/' ~ schema_name | lower ~ '.yml' %}
{{ log("Uploading Cortex Analyst schema '" ~ schema_name ~ "' to " ~ stage_path, info=True) }}
{% do run_query(upload_cortex_schema_sql(schema_name)) %}
{{ log("Successfully uploaded " ~ schema_name, info=True) }}
{% endmacro %}


{% macro create_cortex_stage(stage_name='CORTEX_ANALYST_STAGE') %}
{#
    Create the Snowflake stage for Cortex Analyst schemas if it doesn't exist.
    Stage is created in the cortex schema (same as the model), not target schema.
    
    Usage:
        dbt run-operation create_cortex_stage
        dbt run-operation create_cortex_stage --args '{stage_name: MY_CUSTOM_STAGE}'
#}

{% set cortex_database = var('cortex_database') or target.database %}
{% set cortex_schema = var('cortex_target_schema', target.schema ~ '_cortex_schemas') %}

{% set create_stage_sql %}
    CREATE STAGE IF NOT EXISTS {{ cortex_database }}.{{ cortex_schema }}.{{ stage_name }}
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for Cortex Analyst YAML schema files generated by dbt';
{% endset %}

{{ log("Creating stage " ~ cortex_database ~ "." ~ cortex_schema ~ "." ~ stage_name, info=True) }}
{% do run_query(create_stage_sql) %}
{{ log("Stage created successfully", info=True) }}

{% endmacro %}


{% macro create_cortex_semantic_view_sql(schema_name='ATTENDANCE') %}
{#
    Returns the SQL that creates a Snowflake semantic view from the generated YAML in the model table.
    Uses SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML; the view is created in the cortex schema (same as stage).
#}
{% set cortex_database = var('cortex_database') or target.database %}
{% set table_schema = var('cortex_target_schema', target.schema ~ '_cortex_schemas') %}
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML(
    '{{ cortex_database }}.{{ table_schema }}',
    (SELECT "yaml_content" FROM {{ target.database }}.{{ table_schema }}.generate_cortex_schemas WHERE "schema_name" = '{{ schema_name }}' ORDER BY "generated_at" DESC LIMIT 1),
    FALSE
)
{% endmacro %}


{% macro upload_and_create_cortex_semantic_view_sql(schema_name='ATTENDANCE') %}
{#
    Returns the SQL that (1) uploads the generated YAML to the Cortex stage and
    (2) creates the Snowflake semantic view from that YAML. Use as a single post-hook.
#}
{{ upload_cortex_schema_sql(schema_name) }};
{{ create_cortex_semantic_view_sql(schema_name) }}
{% endmacro %}


{% macro list_cortex_schemas() %}
{#
    List all Cortex Analyst schemas currently in the stage.
    
    Usage:
        dbt run-operation list_cortex_schemas
#}

{% set cortex_stage = var('cortex_stage', '@CORTEX_ANALYST_STAGE') %}

{% set list_sql %}
    LIST {{ cortex_stage }};
{% endset %}

{% set result = run_query(list_sql) %}

{{ log("Cortex Analyst schemas in " ~ cortex_stage ~ ":", info=True) }}
{% if result and result.rows | length > 0 %}
    {% for row in result.rows %}
        {{ log("  - " ~ row['name'] ~ " (" ~ row['size'] ~ " bytes, modified: " ~ row['last_modified'] ~ ")", info=True) }}
    {% endfor %}
{% else %}
    {{ log("  (no schemas found)", info=True) }}
{% endif %}

{% endmacro %}
